//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGioHang
    {
        public int IdSP { get; set; }
        public int IdNCC { get; set; }
        public int IdLoaiSP { get; set; }
        public int IdMucgia { get; set; }
        public int IdKM { get; set; }
        public int IdGioHang { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual GioHang GioHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
